apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-influx
  namespace: ${CICD_GIT_REPO_NAME}
spec:
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-influx
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-influx
      annotations:
        iiidevops.org/project_name: "${CICD_GIT_REPO_NAME}"
        iiidevops.org/branch: "${CICD_GIT_BRANCH}"
        iiidevops.org/commit_id: "${CICD_GIT_COMMIT}"
        iiidevops.org/type: db-server
    spec:
      imagePullSecrets:
      - name: harbor-local
      containers:
        - image: influxdb:2.5.1
          name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-influx
          ports:
            - containerPort: 8086