apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-svc
  namespace: ${CICD_GIT_REPO_NAME}
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-svc
  annotations:
    iiidevops.org/project_name: "${CICD_GIT_REPO_NAME}"
    iiidevops.org/branch: "${CICD_GIT_BRANCH}"
    iiidevops.org/commit_id: "${CICD_GIT_COMMIT}"
    iiidevops.org/type: "web-server"
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-influx
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086